### PR TITLE
fix(request_handler) to read error message from error json body

### PR DESCRIPTION
**Pull request by luca992**
Getting the error message description text from a 400 response is not working. I'm seeing `Unknown error` returned every time it fails for me.

While I haven't actually tested this. I'm pretty sure it should be getting the `error` value here not `message`, refer screen shot:

Screenshot 2024-06-19 at 11 18 50 PM

another example 400 response:
`"{"error":"reached webhook limit"}"`

#### edit:

So this error format above seems to only be returned by the post webhook api.

For other apis errors are returned in this format:

```
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32603,
        "message": "internal error: please contact Helius support if this persists"
    }
}
```

Which is where I think getting `message` came from (still incorrect though as it would need to be accessed by `error.message`)

### CODE REVIEW

**Review by 0xIchigo — CHANGES_REQUESTED** [review]
Nice catch! We should also handle the nested error message case where the format is `{ "error": { "message": "..." }}`. We could do two separate `if let Some(error)` checks where the first is a string and the second is an object. Can you please implement that logic and then I'll be good to merge the PR?

**Comment by luca992** [comment]
what about deserializing to an enum? that could handle both easily. Also do you want that rpc error code to be thrown out?

**Comment by 0xIchigo** [comment]
@luca992 yeah, that works too! The RPC error code would also be helpful

**Comment by luca992** [comment]
done. Fixed the test and added a test for the second varient

**Review by 0xIchigo — APPROVED** [review]
Based. LGTM 🔥

**Pull request merged**
