### PR TITLE
Bump solana to 2.0.x

### PR DESCRIPTION
**Pull request by 4lve**

### CODE REVIEW

**Comment by 0xIchigo** [comment]
gm @4lve ! Unfortunately, it doesn't look like this PR is building correctly. Would you be able to mirror #74 more closely as it seems the versions in there work

**Comment by 0xIchigo** [comment]
And, of course, now it doesn't work with #77 merged, likely because of the inclusion of `mpl-token-metadata` and `spl-token` 💀 @4lve

**Comment by 4lve** [comment]
Yep, we are doomed lol. [this issue has been raised in mpl-token-metadata](https://github.com/metaplex-foundation/mpl-token-metadata/issues/134)

**Comment by 4lve** [comment]
Alr, found that a beta version of mpl-token-metadata support 2.0, I pushed

**Review by 0xIchigo — APPROVED** [review]
Extremely based! Thank you for your contribution 🔥

**Pull request merged**
