### PR TITLE
fix(search_assets): Issue with field deserialization

### PR DESCRIPTION
**Pull request by power-law**
Within the `Asset` type, there was an incorrect `#[serde(rename = "tokenSupply")]` for the `token_info` field. As is, it always returns `None` because there is no `tokenSupply` field in the response body.

### CODE REVIEW

**Comment by power-law** [comment]
I recognize this could just be due to an incoming change on the server-side, so please close if so.

**Review by 0xIchigo — CHANGES_REQUESTED** [review]
Thank you for your contribution! I'd love to try it out. However, it looks like the build is failing

**Comment by gstohl** [comment]
No error is thrown because the field is Optional, the problem remains, the response "token_info" will not get parsed.
A hot fix now is to remove the line 360 in types.rs. To be exact the line:
`#[serde(rename = "tokenSupply")]`

**Review by 0xIchigo — APPROVED** [review]
Actually, I'm going to go ahead and merge this. I'll clean up all the build issues in a separate PR. Thank you for your contributions!

**Pull request merged**
