### PR TITLE
Fix instruction error serialization 0.2.1

### PR DESCRIPTION
**Pull request by levicook**
Fixes

```
Failed to parse transactions for signatures, error: SerdeJson(Error("missing field `InstructionError`", ...))
```

Encountered when calling `helius::Helius.parse_transactions` ala:

```
        match state.helius.parse_transactions(req).await {
            Ok(transactions) => {
                for transaction in transactions {
                    crate::enhanced_transactions::ingest_essentials(&state, transaction).await?;
                }
            }
```

### CODE REVIEW

**Comment by levicook** [comment]
@0xIchigo -- I just patched the release version I was locked into. No idea if this was fixed later, so consider this draft an FYI.

**Comment by levicook** [comment]
also noticed that `instruciton_error` is misspelled after looking at it a hundred other times.

**Comment by 0xIchigo** [comment]
@levicook nice catch! This hasn't been fixed yet, so feel free to mark the PR as ready for review. Also, feel free to update the spelling of `instruction_error`

**Comment by levicook** [comment]
sounds good! corrected the typo & marked ready for review. :shipit:

**Review by 0xIchigo — APPROVED** [review]
Based 🔥

**Pull request merged**
